### ISSUE TITLE
Doesn't work with Webpack 2

### ISSUE THREAD

**Issue by Sieabah** [gajus/to-string-loader#10]
In my Webpack config
`
{
  test: /\.css$/,
  use: ['to-string-loader', 'css-loader']
},
`

`
ERROR in ../~/css-loader!../~/raw-loader!./src/app/app.component.css
Module build failed: CssSyntaxError: css-loader!\node_modules\raw-loader\index.js!app\app.component.css:1:1: Unknown word

> 1 | module.exports = "html,body  {\n  background: #0288D1;\n}\n\n.main {\n  background: #B3E5FC;\n  padding: 20px;\n}\n\n.card-1 { box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24); }\n.card-2 { box-shadow: 0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23); }\n.card-3 { box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23); }\n.card-4 { box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22); }\n.card-5 { box-shadow: 0 19px 38px rgba(0,0,0,0.30), 0 15px 12px rgba(0,0,0,0.22); }\n\n.actionmenu{\n  background: #212121;\n  padding: 0 10px;\n}\n"
    | ^

    at Input.error (node_modules\postcss\lib\input.es6:90:22)
    at Parser.unknownWord (node_modules\postcss\lib\parser.es6:433:26)
    at Parser.other (node_modules\postcss\lib\parser.es6:153:14)
    at Parser.loop (node_modules\postcss\lib\parser.es6:55:22)
    at parse (node_modules\postcss\lib\parse.es6:15:16)
    at new LazyResult (node_modules\postcss\lib\lazy-result.es6:42:24)
    at Processor.process (node_modules\postcss\lib\processor.es6:95:16)
    at processCss (node_modules\css-loader\lib\processCss.js:188:11)
    at Object.module.exports (node_modules\css-loader\lib\loader.js:24:2)
 @ ./src/app/app.component.css 2:21-141
 @ ./src/app/app.component.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
`

**Comment by Sieabah** [comment]
Guess I should also add I'm on _webpack2-beta.28_

**Comment by jorawarsingh** [comment]
same here, any luck with this issue?

**Comment by DiegoYungh** [comment]
Same issue here

**Comment by karolmie1** [comment]
Did you try final webpack2 release? Can you provide repository to reproduce?

**Comment by mareksuscak** [comment]
From what I recently saw it does work w/ webpack 2. I'd just go ahead and close this issue until anyone else objects.

**Comment by Sieabah** [comment]
I haven't tried using it again.
