### ISSUE TITLE
Error if css contains relative url

### ISSUE THREAD

**Issue by colinfang** [gajus/to-string-loader#6]
`styleUrls: ['./app.component.css']`

`loaders: ['to-string', 'css']`

I have also loader for images.

If my css contains

`background: url(../../public/images/gears.gif) no-repeat center center;`

It thows an error:

```
ERROR in app.component.css
Module build failed: /public/images/gears.gif:1
(function (exports, require, module, __filename, __dirname) { GIF89ax
                                                                     
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (app.component.css:6:327)
    at Module._compile (module.js:556:32)
    at Object.exec (webpack-core/lib/NormalModuleMixin.js:88:7)
    at Object.module.exports (to-string-loader/src/to-string.js:6:54)
```

It works if I use 

`background: url(/public/images/gears.gif) no-repeat center center;`

instead.

**Comment by gajus** [comment]
I don't have time to look into this, but would accept a PR.

**Comment by colinfang** [comment]
Seem duplicate #2
