### ISSUE TITLE
Loading materialize.css with font

### ISSUE THREAD

**Issue by mrfuxi** [gajus/to-string-loader#7]
I'm trying to load `materialize.css` and it is dying with error as below. Any advise how to solve it?

```
ERROR in ./~/css-loader!./~/to-string-loader/src/to-string.js!./~/css-loader!./~/materialize-css/dist/css/materialize.css
Module build failed: /app/node_modules/materialize-css/dist/fonts/roboto/Roboto-Thin.eot:1
(function (exports, require, module, __filename, __dirname) { �T
                                                              ^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/node_modules/materialize-css/dist/css/materialize.css:6:74509)
    at Module._compile (module.js:556:32)
    at Object.exec (/app/node_modules/webpack/lib/NormalModule.js:94:6)
    at Object.module.exports (/app/node_modules/to-string-loader/src/to-string.js:6:54)
 @ ./~/materialize-css/dist/css/materialize.css 4:14-151
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main
```

**Comment by gajus** [comment]
Looks like you don't have font loader setup.

This question has nothing to do with `to-string-loader`, though.
